name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version:
        - "1.14"
        # Allocation test fails on 1.15, but works on 1.16. Disabling 1.15 for
        # now.
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
        # Quotes are important: 1.20 is not 1.2
        - "1.20"
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: |
        go test
